name: Daily Wedding Data Scrape

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: make sync

      - name: Run TWN scraper
        run: uv run python -m src.twn.main

      - name: Run BlissfulBrides venue scraper
        run: uv run python -m src.bb.main venues --delay 0.1

      - name: Run BlissfulBrides banquet prices scraper
        run: uv run python -m src.bb.main banquet-prices

      - name: Commit and push data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): automated daily scrape"
          file_pattern: "data/*"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
